name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Dockerhub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dxh30/mytestapp:latest
    
    - name: Push the Docker image
      run: docker push dxh30/mytestapp:latest
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f deployment.yaml
